app:
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 10s
  stack-overflow-client:
    max-retries: 3
    retry-step: 2s
    backoff-strategy: constant
    base-url: https://api.stackexchange.com
  github-client:
    max-retries: 3
    retry-step: 2s
    backoff-strategy: exponential
    base-url: https://api.github.com
  bot-client:
    base-url: http://localhost:8090
    max-retries: 3
    retry-step: 2s
    backoff-strategy: linear
  database-access-type: jpa
  rate-limit-config:
    bucket-capacity: 60
    cache-expiration-duration: 10m
    refill-interval: 1m
  kafka-producer-config:
    bootstrap-servers: "localhost:9092"
    linger-ms: 100
    updates-topic-name: linkUpdates
    acknowledgments: 1
  use-queue: true

spring:
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
