app:
  scheduler:
    enable: true
    interval: 1000s
    force-check-delay: 10s
  stack-overflow-base-url: https://api.stackexchange.com
  github-base-url: https://api.github.com
  bot-base-url: http://localhost:8090

spring:
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
