app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-client:
    base-url: http://localhost:8080
    max-retries: 3
    retry-step: 2s
    backoff-strategy: constant
  rate-limit-config:
    bucket-capacity: 60
    cache-expiration-duration: 10m
    refill-interval: 1m
  kafka-consumer-config:
    auto-offset-reset: earliest
    group-id: tg-bot
    bootstrap-servers: localhost:9092
    updates-topic-name: linkUpdates
    trusted-packages:
      - edu.java.common.dto.linkupdate
  kafka-dlq-producer-config:
    bootstrap-servers: localhost:9092
    linger-ms: 100
    dlq-topic-name: updates_dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - info
          - health
          - prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}
