app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-base-url: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

logging:
  config: classpath:log4j2-plain.xml
