app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-client:
    base-url: http://localhost:8080
    max-retries: 3
    retry-step: 2s
    backoff-strategy: constant
    retry-codes:
      - 500
      - 502
      - 503
  rate-limit-config:
    bucket-capacity: 60
    cache-expiration-duration: 10m
    refill-interval: 1m

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

logging:
  config: classpath:log4j2-plain.xml
