/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer linkId;
    private Integer tgChat;

    public TrackInfo() {}

    public TrackInfo(TrackInfo value) {
        this.linkId = value.linkId;
        this.tgChat = value.tgChat;
    }

    @ConstructorProperties({ "linkId", "tgChat" })
    public TrackInfo(
        @NotNull Integer linkId,
        @NotNull Integer tgChat
    ) {
        this.linkId = linkId;
        this.tgChat = tgChat;
    }

    /**
     * Getter for <code>TRACK_INFO.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>TRACK_INFO.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>TRACK_INFO.TG_CHAT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getTgChat() {
        return this.tgChat;
    }

    /**
     * Setter for <code>TRACK_INFO.TG_CHAT</code>.
     */
    public void setTgChat(@NotNull Integer tgChat) {
        this.tgChat = tgChat;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TrackInfo other = (TrackInfo) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.tgChat == null) {
            if (other.tgChat != null)
                return false;
        }
        else if (!this.tgChat.equals(other.tgChat))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.tgChat == null) ? 0 : this.tgChat.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrackInfo (");

        sb.append(linkId);
        sb.append(", ").append(tgChat);

        sb.append(")");
        return sb.toString();
    }
}
