/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.TgChat;
import edu.java.scrapper.domain.jooq.tables.TrackInfo;
import edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import edu.java.scrapper.domain.jooq.tables.records.TgChatRecord;
import edu.java.scrapper.domain.jooq.tables.records.TrackInfoRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.LINK_ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<TgChatRecord> CONSTRAINT_D = Internal.createUniqueKey(TgChat.TG_CHAT, DSL.name("CONSTRAINT_D"), new TableField[] { TgChat.TG_CHAT.CHAT_ID }, true);
    public static final UniqueKey<TrackInfoRecord> CONSTRAINT_63C = Internal.createUniqueKey(TrackInfo.TRACK_INFO, DSL.name("CONSTRAINT_63C"), new TableField[] { TrackInfo.TRACK_INFO.LINK_ID, TrackInfo.TRACK_INFO.TG_CHAT }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TrackInfoRecord, LinkRecord> CONSTRAINT_6 = Internal.createForeignKey(TrackInfo.TRACK_INFO, DSL.name("CONSTRAINT_6"), new TableField[] { TrackInfo.TRACK_INFO.LINK_ID }, Keys.CONSTRAINT_2, new TableField[] { Link.LINK.LINK_ID }, true);
    public static final ForeignKey<TrackInfoRecord, TgChatRecord> CONSTRAINT_63 = Internal.createForeignKey(TrackInfo.TRACK_INFO, DSL.name("CONSTRAINT_63"), new TableField[] { TrackInfo.TRACK_INFO.TG_CHAT }, Keys.CONSTRAINT_D, new TableField[] { TgChat.TG_CHAT.CHAT_ID }, true);
}
